Repository mojohaus/properties-maven-plugin, pull requests merged in 2023-06, with the labels that each got.

#99 Require Maven 3.5.4+
  pom.xml
Labels: dependencies, maintenance

#103 Add "override" option to preserve existing properties from being overridden
  src/main/java/org/codehaus/mojo/properties/ReadPropertiesMojo.java
  src/test/java/org/codehaus/mojo/properties/ReadPropertiesMojoTest.java
Labels: enhancement

#28 Fix for #27 Unwarranted circular property definition
  src/main/java/org/codehaus/mojo/properties/CircularDefinitionPreventer.java
  src/main/java/org/codehaus/mojo/properties/ExpansionBuffer.java
  src/test/java/org/codehaus/mojo/properties/PropertyResolverTest.java
Labels: bug
