Repository mojohaus/properties-maven-plugin, pull requests merged in 2023-10, with the labels that each got.

#110 Fix unwarranted circular property definition error from CircularDefinitionPreventer
  src/main/java/org/codehaus/mojo/properties/CircularDefinitionPreventer.java
  src/test/java/org/codehaus/mojo/properties/PropertyResolverTest.java
Labels: bug

#112 read-project-properties optimization - set all properties in one call
  src/main/java/org/codehaus/mojo/properties/ReadPropertiesMojo.java
Labels: enhancement

#113 Introduce properties manager for easy implements other properties formats
  pom.xml
  src/it/read-project/invoker.properties
  src/it/read-project/main.properties
  src/it/read-project/main2.txt
  src/it/read-project/pom.xml
  src/it/read-project/src/main/resources/test.txt
  src/it/read-project/verify.groovy
  src/main/java/org/codehaus/mojo/properties/AbstractPropertiesMojo.java
  src/main/java/org/codehaus/mojo/properties/AbstractWritePropertiesMojo.java
  src/main/java/org/codehaus/mojo/properties/ReadPropertiesMojo.java
  src/main/java/org/codehaus/mojo/properties/SetSystemPropertiesMojo.java
  src/main/java/org/codehaus/mojo/properties/WriteActiveProfileProperties.java
  src/main/java/org/codehaus/mojo/properties/WriteProjectProperties.java
  src/main/java/org/codehaus/mojo/properties/managers/JdkPropertiesManager.java
  src/main/java/org/codehaus/mojo/properties/managers/PropertiesManager.java
  src/test/java/org/codehaus/mojo/properties/ReadPropertiesMojoTest.java
  src/test/java/org/codehaus/mojo/properties/managers/JdkPropertiesManagerTest.java
Labels: enhancement

#115 Add documentation about plugin limitations
  src/site/apt/index.apt
Labels: maintenance
